### ISSUE TITLE
Будет ли в дальнейшем интеграция обложек?

### ISSUE THREAD

**Issue by vorobbkk** [ArtemIzmaylov/aimp_VK#3]
Добрый день. Очень жду появления интеграции обложек у треков из ВК, или хотя бы возможность ставить обложки самостоятельно чтобы они хранились в кэше на пк

**Comment by ArtemIzmaylov** [comment]
https://github.com/ArtemIzmaylov/aimp_VK/releases/tag/1.06.77

**Comment by vorobbkk** [comment]
появилась проблема, не показываются обложки, хотя апи обложек включен к песне
![image](https://github.com/ArtemIzmaylov/aimp_VK/assets/79831008/da1777b1-862e-44b0-8da4-d0a7d0ebb01d)

**Comment by ArtemIzmaylov** [comment]
Со стороны плеера разрешена загрузка обложек с интернета?

**Comment by vorobbkk** [comment]
нет, параметр был выключен. спасибо, теперь проблема решена
